### ISSUE TITLE
Gitlab Runner: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by simonavril** [awslabs/tecli#17]
Our runners fail periodically quite a lot with the same error:

panic: runtime error: invalid memory address or nil pointer dereference.

```
$ ./tecli variable update-by-key --workspace-id=${TFC_WORKSPACE_ID} --key=ci_deploy_number --value= --category=terraform --sensitive=false
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8668f4]
goroutine 1 [running]:
github.com/awslabs/tecli/cobra/controller.variableRun(0xc00015cb00, 0xc0000cd1a0, 0x1, 0x6, 0x0, 0x0)
	/home/runner/work/tecli/tecli/cobra/controller/variable.go:158 +0x12d4
github.com/spf13/cobra.(*Command).execute(0xc00015cb00, 0xc0000cd140, 0x6, 0x6, 0xc00015cb00, 0xc0000cd140)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc00015c2c0, 0xc000000180, 0x200000003, 0xc000000180)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/awslabs/tecli/cobra/cmd.Execute()
	/home/runner/work/tecli/tecli/cobra/cmd/root.go:30 +0x31
main.main()
	/home/runner/work/tecli/tecli/main.go:21 +0x25
```
Trying to understand the cause of this issue as it sometimes does not fail.

Tecli is installed in a job with

```yaml
tecli:
  stage: tools
  rules:
    # We will need tecli for deploying
    - if: '$DEPLOY_APP == "true"'
  script:
    - 'wget --quiet https://github.com/awslabs/tecli/releases/download/0.3.0/tecli-linux-amd64 -O tecli'
    - chmod +x tecli
  artifacts:
    paths:
      - 'tecli'

```
